### ISSUE TITLE
White on yellow text is hardly readable

### ISSUE THREAD

**Issue by mccartney** [meikpiep/gauguin#108]
![Screenshot_20240310-224759.jpg](https://github.com/meikpiep/gauguin/assets/762437/c3ac8eb2-5650-4240-94a5-49b69e95c93e)

The difficulty levels are displayed with white text over yellow background. This is hardly readable.

0.21.0

**Comment by meikpiep** [comment]
FYI: Just released https://github.com/meikpiep/gauguin/releases/tag/v0.22.1, containing this fix and another, major one.
