### ISSUE TITLE
Meta data description: Grammar, and Spelling Fixes.

### ISSUE THREAD

**Issue by MikeStirner** [meikpiep/gauguin#140]
1. "You can use it to relax or to solve difficult grids to your opinion."
Change to: You can use it to relax or to solve difficult grids. Whatever you prefer.

2. "difficulty (covering a incresing number of game variants)"
Change to: difficulty (covering an increasing number of game variants)

**Comment by meikpiep** [comment]
Fixed and committed in the next minutes, including suggested changes of @HarmfulBreeze contained via comment at Weblate https://hosted.weblate.org/translate/gauguin/gauguin-metadata/en_US/?q=has:comment#comments:

> Shouldn't "usage of single cells" be "usage of single cages"? Also bullet points should probably be em-dashes instead of minuses.

Thanks for the optimizations! If you have faith in optimizing or rewriting the description, let me know.
