### ISSUE TITLE
[Feature request] new stats display

### ISSUE THREAD

**Issue by BertusVulgaris** [meikpiep/gauguin#148]
It would be great to visualize time spent on a puzzle vs difficulty, as a scatter plot.

**Comment by meikpiep** [comment]
That's a great idea!

The lib currently used for diagrams (Vico) does not support scatter diagrams. I will think about if we can support a diagram serving the needs.

**Comment by meikpiep** [comment]
@BertusVulgaris I just released version 0.30.0 https://github.com/meikpiep/gauguin/releases/tag/v0.30.0 containing the scatter plot, thanks for the idea!

**Comment by meikpiep** [comment]
See further info and discussion here regarding statistics: https://github.com/meikpiep/gauguin/discussions/220#discussioncomment-10647977
