### ISSUE TITLE
Position of "0" in selection vs pencil grid don't match 

### ISSUE THREAD

**Issue by drkthomp** [meikpiep/gauguin#157]
In the pencil mark grid, 0 is first, whereas in the selection bar it is last. Feature wise I would prefer if it were first or if there was an option to decide, but not matching at all seems like a bug.

[Screenshot_20240421-224137_Gauguin](https://github.com/meikpiep/gauguin/assets/4887015/2f6f540c-775d-4061-baf0-745ee1f23ca3)

(Also love this game!)

**Comment by meikpiep** [comment]
Sorry for the delay - the inconsistency is definitely a bad thing. I have no definite opinion which way round would be best and want to avoid another option.

I will try to play a few such games to get a feeling.

**Comment by meikpiep** [comment]
I got to the opinion that the 3x3 pencil marks should follow the key pad layout, so it will look like this:

![grafik](https://github.com/meikpiep/gauguin/assets/92228913/ef12e5d4-fc79-42b6-b17a-8fa114754573)

I think the "1-2-3" in the first line of the key pad is a common settings to be preserved, but let's see what the other users mean.

**Comment by meikpiep** [comment]
A 7x7 sample will make it more clear: 

![grafik](https://github.com/meikpiep/gauguin/assets/92228913/3f53844c-49e0-4cae-9dd2-918e5f98bb1f)

**Comment by meikpiep** [comment]
Just merged the changes, will get into the next release.

**Comment by meikpiep** [comment]
FYI: I optimized the layout a bit, see here: 
![grafik](https://github.com/meikpiep/gauguin/assets/92228913/bf8f69b0-8381-44a8-80b0-9bc2055c9468)

**Comment by meikpiep** [comment]
FYI: I just released version 0.26.0 including this change. Should be online via Google play store in 1-2 days and via F-Droid in 3-6 days.
