### ISSUE TITLE
Game top bar: Corrupted layout using a rtl language

### ISSUE THREAD

**Issue by meikpiep** [meikpiep/gauguin#158]
See Screenshot. Should be a straight forward fix. (Check the difficulty popup when fixing this.)

![٢٠٢٤٠٤٢٣_٠٥٤١٠٨](https://github.com/meikpiep/gauguin/assets/57833737/01fc4afb-e889-49c6-9356-8d17aca73585)

_Originally posted by @albaroty in https://github.com/meikpiep/gauguin/issues/143#issuecomment-2071310380_

**Comment by meikpiep** [comment]
@albaroty I just commited a fix, the top frame will now look likes this, does this look right in your opinion? 

![grafik](https://github.com/meikpiep/gauguin/assets/92228913/85a9e6bf-e709-425b-84a6-fe9cbdad959d)

**Comment by albaroty** [comment]
Yes wonderful 

Thank you
