### ISSUE TITLE
New game stuck in loading screen

### ISSUE THREAD

**Issue by nobbyyyy** [meikpiep/gauguin#169]
After choosi g new game he not accept numbers and there is a big fair wheel in the front?

**Comment by meikpiep** [comment]
Can you reproduce this? Do you remember what game variant to tried to play?

**Comment by meikpiep** [comment]
I'm closing this issue as no further info was provided. I stumbled upon an issue which may be related to this and got solved via version 0.26.0 which has just been released.

Feel free to open a new issue or reopen it if you could supply any additional infos.
