### ISSUE TITLE
Pencil marks not removed when restarting game

### ISSUE THREAD

**Issue by nach0** [meikpiep/gauguin#18]
When I'm stuck on a game and decide to restart from scratch, the "Restart game" button clears all the numbers I entered as definitive, but not the pencil marks (the possible values of a cell). I would expect "Restart game" to clear the pencil marks too.

Version 0.10.0, downloaded from F-Droid.

**Comment by meikpiep** [comment]
Thanks for reporting, this will be fixed in the next version which will be ready via F-Droid in circa one Werk.

**Comment by meikpiep** [comment]
Just released version 0.10.1, fixing this issue: https://github.com/meikpiep/gauguin/releases/tag/v0.10.1

**Comment by meikpiep** [comment]
FYI: Version 0.10.1 including the fix just arrived at the F-Droid APP store.
