### ISSUE TITLE
Solved grid gets not discovered as solved, game continues

### ISSUE THREAD

**Issue by guy-teube** [meikpiep/gauguin#194]
Hello,
I've just discovered the game, maybe I've misunderstand the behaviour, don't blame me :)
When I finish a game, nothing happens. The timecontinues to flow. When I request the solution, it says there is no error.
So why the app doesn't say me the game is ended?
Thank you

**Comment by meikpiep** [comment]
You're welcome!

There is one rare bug which I cannot reproduce on any of my devices: https://github.com/meikpiep/gauguin/issues/131
Can you share a screenshot with a solved grid, including of popup when pressing the '?' button?

**Comment by guy-teube** [comment]
Here the screenshots: 

![Screenshot_20240714-145740_Gauguin](https://github.com/user-attachments/assets/2b5a3b29-4755-4f2e-acf5-b9bde34151c0)

![Screenshot_20240714-145751_Gauguin](https://github.com/user-attachments/assets/ccf2d92b-c8e0-4e49-9d7f-2950904baa85)

I use a Google Pixel 4a, with LineageOS 21 (Android 14).

**Comment by meikpiep** [comment]
Thanks for the screenshot, this helps a lot.

The small numbers you entered via short pressing the number buttons are so called 'pencil marks'. I you do a long press (works on the number buttons an on a cell containing exactly one pencil mark) the number gets filled in, in bold and rather huge, indicating that you are sure this cell should get this value.

The '?' button only validates values entered via long pressing, so the game from the screenshot will always show zero errors.

Does this solve your problem?

**Comment by guy-teube** [comment]
Ok you're right, I didn't understand correctly!
With these big numbers, I have the expected popup of victory :)
Thank you
