### ISSUE TITLE
Slightly overlapping items in portrait mode

### ISSUE THREAD

**Issue by mccartney** [meikpiep/gauguin#203]
I have always played in portrait mode, but by accident opened the app in landscape. And the ? button slightly overlaps with the other icons as per the screenshot:
![Gauguin20240804.jpg](https://github.com/user-attachments/assets/abb43c48-4eb5-4ace-bf33-f88ed92ad88f)

Observed in Oneplus 6.

(Minor issue, I don't need it for anything, just reporting)

**Comment by meikpiep** [comment]
Should be solved in the next version, thanks for reporting!
