### ISSUE TITLE
cell value overlaps pencil marks

### ISSUE THREAD

**Issue by ashkitten** [meikpiep/gauguin#21]
![Screenshot_20231111-172236](https://github.com/meikpiep/gauguin/assets/9281956/0b7a1f7a-4f2a-4b08-8d21-f6a2cddb0da0)
in 3x3 grid mode:
![Screenshot_20231111-172438](https://github.com/meikpiep/gauguin/assets/9281956/6bac1819-a287-4ba6-8bdf-97f54d309833)

**Comment by meikpiep** [comment]
Thank you for reporting this.

I will optimize the pencil marks soon and leave a comment here.

**Comment by meikpiep** [comment]
I managed to optimize the pencil marks, which solves problems with values up to 1..9, see screenshots. Large cages the large numbers are still a problem to be solved in the future.

![grafik](https://github.com/meikpiep/gauguin/assets/92228913/aed5f381-8a19-4da5-9c7b-217f13fd84df)
![grafik](https://github.com/meikpiep/gauguin/assets/92228913/d62d0310-23e4-46a9-8146-a38f575fd8fd)

**Comment by meikpiep** [comment]
Included in todays release https://github.com/meikpiep/gauguin/releases/tag/v0.11.0

Via Google play, its already productive.
In F-Droid, we have to wait ~5-7 days.

**Comment by meikpiep** [comment]
The fix is part of version 0.11.0, released yesterday: https://github.com/meikpiep/gauguin/releases/tag/v0.11.0

This a already online via Google play store, F-Droid will arrive with usual delay, may be in 4-6 days.

Please report related issues if they still persist from 0.11.0 on.
