### ISSUE TITLE
Ferris-Wheel lib unavailable since JCenter shutdown

### ISSUE THREAD

**Issue by linsui** [meikpiep/gauguin#222]
Because JCenter has shutdown.

https://gitlab.com/fdroid/fdroiddata/-/jobs/7828377414

Could you please migrate from jcenter libs?

**Comment by meikpiep** [comment]
Thanks for the heads up, I just released https://github.com/meikpiep/gauguin/releases/tag/v0.30.2 with a workaround.

**Comment by licaon-kter** [comment]
adding a random binary is not an workaround :( https://github.com/meikpiep/gauguin/commit/9013a870a3efc29fd67a428c1e25e4088ff3bb61

**Comment by meikpiep** [comment]
@licaon-kter @linsui Do you mean it will not work or it should only be temporary?

I created an issue at the dependency to get things going: https://github.com/iglaweb/Ferris-Wheel/issues/7

Any better ideas are welcome.

**Comment by licaon-kter** [comment]
Will work for you, won't work for F-Droid.

Maybe we can build from source? The app is build reproducible so when building we'll need for the lib to be too

**Comment by licaon-kter** [comment]
Don't care which version we build, that's up to you and your future self :)

**Comment by meikpiep** [comment]
It would be helpful if you could answer my question, as I'm trying to gather info about want is technically possible and wanted via F-Droid. Could you clarify what you mean by "building from source" in a non-abstract way? If so, I would be glad to understand what you mean.

I got the point that its dependencies builds have to be reproducible.

Will the current state of containing a local AAR file in the code repo break F-Droid build?

**Comment by linsui** [comment]
You want a workaround? Just use https://jitpack.io/#iglaweb/Ferris-Wheel. :)

**Comment by meikpiep** [comment]
@linsui Would be happy to use it but Jitpack is not able to version the latest versions like 1.2 this app is using. :-(

**Comment by linsui** [comment]
Lol, the lib depends on other jcenter libs so jitpack can't build it. So I thought you need to switch to another lib since we can't build this lib.

**Comment by meikpiep** [comment]
Okay, so there is switching the lib, fork the lib to exclude the JCenter stuff or magically get the lib fixed upstream.

**Comment by linsui** [comment]
Yes. :) I don't think upstream will fix this old lib though.

**Comment by meikpiep** [comment]
@linsui I share your opinion, thank you for your thoughts. Can you disable the F-Droid build for version 0.30.2 while I'm getting JCenter out of the way?

**Comment by licaon-kter** [comment]
@meikpiep already disabled

**Comment by meikpiep** [comment]
@linsui FYI I just released a version https://github.com/meikpiep/gauguin/releases/tag/v0.30.3 which does not use the affected library (it only used for a loading animation) and avoids JCenter completely.

I will fork the lib, hopefully temporary, to make it work without JCenter and update its dependencies, if this works out.

**Comment by meikpiep** [comment]
I forked the Ferris Wheel lib, find it at https://github.com/meikpiep/Ferris-Wheel

Since yesterday, there is a new release of the lib available via JitPack and used in this app. The animation works as before, I updated its dependencies and build system. If the original maintainer gets active, I will see to provide pull requests, if not, I will support it as long as needed via Gauguin.
