### ISSUE TITLE
Alternative representation of division operator

### ISSUE THREAD

**Issue by orontee** [meikpiep/gauguin#227]
# Context

The symbol `÷` looks like a `+` to my old eyes.

# Proposal

Add setting to change the reprensentation of the division operator to the standard `/`.

**Comment by meikpiep** [comment]
Thanks for reporting, I stumbled into this but did have a good idea how to solve it.

Thinking about avoiding a new preference and directly switching to `\`.

@HarmfulBreeze do you have any other thoughts or possible solutions? I think that the current font renders both `+` and `÷` in a similar way. We could try switching the font, but I'm still in love with the numerical glyphs. The `\` is easy to read and distinguish, but its not very appealing.

**Comment by HarmfulBreeze** [comment]
Seems like a good accessibility improvement. I'm fine with both proposals, but I'd consider switching fonts first before considering switching to `/`, as it is a font issue, and not a "which character is appropriate here" one. But that's just my two cents :)

**Comment by meikpiep** [comment]
@HarmfulBreeze Sometimes, two cents make quite a difference. :-) (Should be read like a kind of Thank You.)

I came up with changing the Font from 'Lato' to 'Inter' (see screenshot). My main concern was to have all four mathematical operator's chars to be distinguished easily. The second concern was that I like the resulting design of the grid.

I hope that this change solves the issue - if it continues, please re-open the issue, then I will be happy to add the preference suggested by @orontee.

![grafik](https://github.com/user-attachments/assets/d1363ce4-4882-4a40-8497-43b39cd48c43)

**Comment by orontee** [comment]
> I hope that this change solves the issue - if it continues, please re-open the issue, then I will be happy to add the preference suggested by @orontee.

I'll told you after it has been published. It looks better from the screenshot.

Whatever, thank you very much for your time!

**Comment by meikpiep** [comment]
FYI, version 0.31.0 https://github.com/meikpiep/gauguin/releases/tag/v0.31.0 has been released just now.

Should be available in 2-3 days via F-Droid and in one day via Play Store.

**Comment by orontee** [comment]
My Gauguin was upgraded yesterday and I can confirm it's better now. Issue solved! 🎆
