### ISSUE TITLE
Monochrome app icon

### ISSUE THREAD

**Issue by mueller-ma** [meikpiep/gauguin#23]
The app doesn't support a monochrome launcher icon on Android 13.

**Comment by meikpiep** [comment]
Good point, will be added soon.

**Comment by meikpiep** [comment]
Just committed the icon, will be available with the next version.

**Comment by meikpiep** [comment]
Included in todays release https://github.com/meikpiep/gauguin/releases/tag/v0.11.0

Via Google play, its already productive.
In F-Droid, we have to wait ~5-7 days.

**Comment by mueller-ma** [comment]
Thanks!
