### ISSUE TITLE
the game doesn't register the numbers I put in 

### ISSUE THREAD

**Issue by usernamejk** [meikpiep/gauguin#244]
it says 0 mistake no matter what I put in. and even if I don't finish the game and tap Show Solution, it says game solved. and it never gets registered in the statistics, where all games stay unsolved even when I finished a lot of them. am i doing something wrong with it??
![Screenshot_20241117-015224](https://github.com/user-attachments/assets/198a456e-28da-4acb-8fcc-7ed0b6df3e2d)
![Screenshot_20241117-015810](https://github.com/user-attachments/assets/0b46fc62-9324-4c18-9037-e36723361461)

**Comment by meikpiep** [comment]
These small numbers indicate a possible number of that cell.

Long press either a number button or a cell containing a single small number to actually fill the cell with a large one.

**Comment by usernamejk** [comment]
😅😅thank you so much!!
