### ISSUE TITLE
Supporting Sudokus

### ISSUE THREAD

**Issue by meikpiep** [meikpiep/gauguin#245]
Hey, because your app's layout is very similar to sudoku, any plan's on adding sudoku game in gauguin or make another app? I don't know much, but maybe it would be easier because only the functionality is different but all layout of app will be same. 
I use libresudoku but its's input layout functionality is not good as yours (buttons are small and it don't use gestures). Thought i created a issue on their's repo today, maintainer's not very active on opened issues.

_Originally posted by @nitinsooni in https://github.com/meikpiep/gauguin/issues/201#issuecomment-2476087480_

**Comment by meikpiep** [comment]
@nitinsooni Sorry for the late reply.

I admit the possibility of adding soduko, but it is unlikely to happen in the near future.

The causes are broad: Gauguin currently gets developed mainly by myself and I have a list of features which I want to add/optimize (e.g. new generation algorithm and a better difficulty rating, having an overall smooth app which good test coverage etc. pp.). I personally do not play sudoku, so to make this happen, there should be another dev to step in. I like sudokus, please don't get me wrong - but maintaining features no dev will use by itself is tricky.

I would strongly prefer to add a sudoku mode to Gauguin rather than maintaining a second app, as this leads to more overhead.

The sudoku feature will add a relevant complexity, so in my eyes, this would be a so called "scope creep" for now. May be, this will change in the future.

**Comment by nitinsooni** [comment]
Yeah, and after seeing the response in this thread, it seems most people don't want this feature also.
Still, thanks for giving it your thought.
