### ISSUE TITLE
Reveal cell/cage not always working

### ISSUE THREAD

**Issue by mueller-ma** [meikpiep/gauguin#25]
Sometimes pressing "show cell" or "show cage" it only shows a snackbar "the puzzle is hard, eh" and nothing else happens.

**Comment by meikpiep** [comment]
Just committed a fix - thought I tested revealing a few times, I'm not totally sure that the issue is completely gone.

**Comment by meikpiep** [comment]
Included in todays release https://github.com/meikpiep/gauguin/releases/tag/v0.11.0

Via Google play, its already productive.
In F-Droid, we have to wait ~5-7 days.
