### ISSUE TITLE
Dynamic colors

### ISSUE THREAD

**Issue by mueller-ma** [meikpiep/gauguin#28]
The app could use the theme colors provided by the OS (requires Android 13).

https://developer.android.com/develop/ui/views/theming/dynamic-colors

**Comment by meikpiep** [comment]
Will be done.

I can't give a timeline as the current color usage is a kind of creative :-), so I will have to clean it up to support the dynamic colors by using the universal semantics of the colors. There is a slight risk that the two additional colors which are in use by the custom theme are a burden to this, just a warning to my self.

**Comment by meikpiep** [comment]
Sorry for not given a status here.

This is definitely in my list, I'm working on it, but: 1. I'm working on other things regarding Gauguin and 2. I only want to include this if the UI looks really cool via dynamic colors. I guess, it will take some time.

**Comment by meikpiep** [comment]
Just released version 0.19.0 containing dynamic colors. Thanks for your patience!

Will be online at Play Store next day and at F-Droid in ~2-4 days.

**Comment by mueller-ma** [comment]
Thanks!

**Comment by mueller-ma** [comment]
The upper orange status bar (where the difficulty in stars and the time is) is still hardcoded to orange.

**Comment by meikpiep** [comment]
Overseen.

**Comment by meikpiep** [comment]
Fix commited, will be included in next release.

**Comment by meikpiep** [comment]
Just released 0.19.1 with fix included: https://github.com/meikpiep/gauguin/releases/tag/v0.19.1
