### ISSUE TITLE
Undo - Nr of mistakes wrong

### ISSUE THREAD

**Issue by mh-tp** [meikpiep/gauguin#31]
if an error was made that conflicts with an already found number you get 2 (or 3 if 2 conflicts) instead of 1 error. if you press "undo" 1 error remains

**Comment by meikpiep** [comment]
Should be already fixed in the code, I stumbled into this, too. There should be 1 mistake, buy both cells should be highlighted to express that there is a duplicate.

**Comment by meikpiep** [comment]
Just released version 0.13.0, fixing this: https://github.com/meikpiep/gauguin/releases/tag/v0.13.0

Should arrive on Google play in a few hours and via F-Droid after the next build, may be in 3-6 days.
