### ISSUE TITLE
Math box outline not always clearly visible

### ISSUE THREAD

**Issue by Dacid99** [meikpiep/gauguin#32]
Hi i absolutely love the game and have already spent much more time on it than i probably should xD. 
Depending on the lighting its sometimes hard to see the outline of the math boxes, currently colored light blue. Maybe that could be fixed by changing to a color that is easier to distinguish from the background.
Thank you for the amazing work!

**Comment by Dacid99** [comment]
Mostly in light mode. Btw i think it would be nice to make 'system setting' the default over light mode in case it isnt already.

**Comment by meikpiep** [comment]
I will look after the boxes to fine tune the colors.

The default color settings are a bit delicate, as I am not a satisfied with the overall look of the game in light theme, but that's another point. I'm currently learning what options the users want and prefer and that's a good thing. I had the not-so-realistic standpoint that each user would love the crafted dark theme as much as myself. :-)

**Comment by Dacid99** [comment]
Youre right the dark theme is very nice, i just set it as default. Thank you for the close-to-instantaneous response!

**Comment by meikpiep** [comment]
btw, what size are the puzzles that you play? Which form factor is your device?

**Comment by Dacid99** [comment]
Right now 5x5 transitioning to 6x6. I play both on an Samsung A40 and Samsung A32

**Comment by meikpiep** [comment]
FYI: I'm fingering on an updated light theme to be more directly using the colors of Paul Gauguin and I will keep an eye on readability of the grid.

**Comment by meikpiep** [comment]
I just released version 0.16.0 https://github.com/meikpiep/gauguin/releases/tag/v0.16.0, including an overhaul of the light theme regarding the grid. Fell free to test and give any feedback, re-open this issue if you think that the initial problem was not solved.

Should be ready via Google play in a few hours and via F-Droid in 3-6 days.
Thanks for reporting!

**Comment by Dacid99** [comment]
Thank you very much!
