### ISSUE TITLE
Division with result 0 is marked as a wrong calculation

### ISSUE THREAD

**Issue by stella-sf** [meikpiep/gauguin#33]
![Screenshot_20231122-155038](https://github.com/meikpiep/gauguin/assets/119541172/c146ab14-0869-4aa0-9015-8bf6895f4e2f)
As you can see in the screenshot, the box labeled as `0/` is highlighted in red, meaning there is a wrong calculation in it. In reality, the calculation 0/1 is fine and produces the desired result. The puzzle is still recognized as solved. I presume that the calculation checker for division somehow interprets this as 1/0, maybe because the usual rule is that the larger number must be the numerator for the calculations to work out.

**Comment by meikpiep** [comment]
Thanks for reporting with such a great detail!

**Comment by meikpiep** [comment]
Your analysis was precise, bug fix will follow asap.

Your reporting is much appreciated.

**Comment by meikpiep** [comment]
Just released version 0.13.1, fixing this issue: https://github.com/meikpiep/gauguin/releases/tag/v0.13.1

Will be on Google play in a few hours and on F-Droid via the next build, 3-6 days.

**Comment by meikpiep** [comment]
FYI: 0.13.1 arrived via F-Droid today.
