### ISSUE TITLE
Feature request: More statistics

### ISSUE THREAD

**Issue by ghost** [meikpiep/gauguin#36]
It would be very nice if we had "best time, worse time etc.." in statistics.

**Comment by meikpiep** [comment]
I definitely want to implement more statistics. I have some ideas how to deal with the huge number of game options. But this is still an early stage.

How many game variants (games with different options) do you actually play?

**Comment by ilija-culap14** [comment]
We play (my wife and me) mostly 6x6. 
P.S. Thank you for such great game

**Comment by meikpiep** [comment]
FYI: I'm aware of the feature request, but it will take time as I would like to see some amazing statistics and the current implementation is not suited to cover different grid variants well.

**Comment by meikpiep** [comment]
Finally, I just released version 0.20.0 with statistics of all games played, see https://github.com/meikpiep/gauguin/releases/tag/v0.20.0

Should be online tomorrow via Google play, F-Droid will build it in ~2-5 days if the global F-Droid karma is willing.
