### ISSUE TITLE
numbers from 1 to 9

### ISSUE THREAD

**Issue by enboig** [meikpiep/gauguin#37]
I play https://github.com/queler/holokenmod but it is starting to look outdated. Yours look similar, could you make number range selectable?

And I really love your long click, save time.

**Comment by meikpiep** [comment]
This game is indeed based on HoloKenMod. :)

Do you mean the lower part Seen in this screenshot? You can actually change which numbers are used. On the long run, it would like to display the numbers which will be used to enhance the UI.

Does this solve your problem?

![Screenshot_20231205-090053_1](https://github.com/meikpiep/gauguin/assets/92228913/2bf32032-129b-404e-836c-9a63f721d466)

**Comment by enboig** [comment]
I didn't test your app enough before posting; I was searching the option in "settings", not in "new game".

Thanks, I will play it more before posting anything else ;-)

**Comment by meikpiep** [comment]
You are welcome.
