### ISSUE TITLE
Zero puzzles solved in statistics

### ISSUE THREAD

**Issue by mccartney** [meikpiep/gauguin#41]
I have certainly completed a few games already and  enjoy the app. Yet the Statistics page shows zero puzzles solved.
![Screenshot_20231211-202556.jpg](https://github.com/meikpiep/gauguin/assets/762437/c68202c2-78a0-44d6-b2b7-d20b513f4352)

**Comment by meikpiep** [comment]
Which version do you run?

**Comment by mccartney** [comment]
0.14.0

**Comment by meikpiep** [comment]
I could not reproduce this error yet.

Are you solving the grids without any help via the overflow menu at the bottom right corner? Do you see confetti when finishing a game?

**Comment by mccartney** [comment]
Yes on both.

BTW I started a new game yesterday and it finally showed up. So maybe the error is gone.

![Screenshot_20231214-204235.jpg](https://github.com/meikpiep/gauguin/assets/762437/064cd9a4-5f36-49ac-9db8-32e831e4f8ca)

**Comment by meikpiep** [comment]
Weird... Would be cool if you watch and report here if the statistics are now working as opposed or if the problem persists.

**Comment by mccartney** [comment]
It started to work now.
I am not sure what happened. The only explanation I could find is that maybe the sequence of events was:

- me starting some games
- the app gets updated past 0.13.0 which solved a bug with zero statistics
- I continue playing without starting a new game
- I report the bug which supposedly affected 0.14.0

I think we can close this issue (for now).
