### ISSUE TITLE
Previous scores

### ISSUE THREAD

**Issue by mccartney** [meikpiep/gauguin#42]
It'd be nice if one could see their own previous times for solving puzzles of respective kind. AFAICT currently you only get the "best score" or not kind of information.

**Comment by meikpiep** [comment]
I definitely want to enhance the statistics. This will be a huge change as there are a lot of variants to choose from. The current idea is to support let's say 20 variants and showing the play time etc. of the last games of these 20 variants. If you have any specific ideas, feel free.

**Comment by meikpiep** [comment]
Closing this in favour of #36.
