### ISSUE TITLE
How to use Fast Finishing Mode?

### ISSUE THREAD

**Issue by Naomitr0n** [meikpiep/gauguin#43]
I saw that the latest release has a "Fast Finishing Mode", but I haven't been able to figure out how to use it or fully what it does. I've enabled it in settings but I haven't noticed any difference.

I might just be an idiot, but is the UI supposed to remain the same or is something supposed to activate when I put three pencil marks in the same square? Or is it any square as long as it's three pencil marks in a row? (Or am I supposed to e.g. add 6, remove 6, then add 6 as a pencil mark as a workaround to a button? I can't tell)

This is the part that I'm confused about:

> The core feature (rapidly entering numbers) should already work, the mechanism to activate it is still in flow. Currently, entering three single pencil marks via long tapping consecutively will activate it. The ui elements blocking the keypad are far from finished, but functional and highly visible.

I was originally under the assumption that the last sentence meant the "You've won" toast that covers most of the bottom row of numbers when you hit the new game button until either it disappears or you swipe it away, and might've been talking about an "in progress" fix to have it not block the keypad anymore, but the more I read it the more it sounds like I'm missing something.

BTW, F-Droid does a great job auto-updating this app, but release notes don't show within F-Droid, so I have to always check the releases tab to see changes -- don't know if that should be a separate issue ticket or if it's a quick fix.

**Comment by meikpiep** [comment]
Thank you for asking!

Sorry for making you feel so, that was not supposed to be. I see I have to update the release notes.

How it works right now: You need at least three cells with pencil marks, say cell 1 has '1', cell 2 has '1, 2', cell 3 has '1,2,3', all three in a line. And hopefully various other cells with pencil marks.

1. When you long tap on cell 1, the 1 gets written. Then cell 2 holds only the remaining 2 which you fill by long tap on the cell 2. Do the same with cell 3.
1. Caution: The mode currently works only if you fill all three cells without any inyrraction of the number buttons, staying all in the grid itself.
1.  Now, the game switches into Fast Finishing Mode, indicated by a huge overlay covering the number buttons next to the grid.
1. From now on, each tap on a cell with a single pencil mark gets filled directly. So you are now able to fill as much cells as get a single pencil mark while filling other cells.

Does this help?

The version Info's are a very good point and I was not aware of it. Would be nice to have a ticket about that. :-) I can create one later this day, so it won't be forgotten.

**Comment by Naomitr0n** [comment]
Ohhhhhhh okay, I got it now. I think a wording change on the settings page would do a lot then.

Right now it's "enter numbers directly by tapping on single pencil marks" which I had trouble understanding too. Something like "Fill squares with one pencil mark by short tap after three filled with long tap" would definitely help a lot I think.

My mix-up was the release notes saying "entering three single pencil marks via long tapping consecutively will activate it" -- I have it set so long-pressing the *keypad* enters a pencil mark, so I just assumed you meant long-pressing the number on keypad, not the square itself, and I further assumed that the setting meant I would tap three pencil marks in a row somewhere to get the new mode to pop up.

Works great now, thank you for clarifying! :)

**Comment by Naomitr0n** [comment]
F-Droid issue split out to #44 -- closing this issue

**Comment by meikpiep** [comment]
Reopening, to do: Clarify the release notes as Naomitr0n suggests.

**Comment by meikpiep** [comment]
Updated description here: https://github.com/meikpiep/gauguin/releases/tag/v0.15.0
