### ISSUE TITLE
F-Droid doesn't show release notes

### ISSUE THREAD

**Issue by Naomitr0n** [meikpiep/gauguin#44]
When a new version is released, there's no section showing the release notes

**Comment by meikpiep** [comment]
Until now, I thought that F-Droid did not incorporate the meta data with the changes. But I found out that they are display on the website here: https://f-droid.org/de/packages/org.piepmeyer.gauguin/

I will have to investigate if this is a kind of intended or not. Other F-Droid packages in the app show the changrlog and I think it is only shown if the app uses the fastlane format and not the triple-t one this app uses.

Does any reader have a clue so I don't have to ask at F-Droid?

**Comment by meikpiep** [comment]
I could switch to fastlane if this solves the problem, just to say it. Otherwise, I would stay to triple-t as I am planing to do the Google play management via API and the triple-t Gradle plugin.

**Comment by meikpiep** [comment]
@Naomitr0n Gauguin has been migrated to Fastlane metadata.

Version 0.29.0 is currently build via F-Froid and should be shipped in the next days. If everything works as supposed, we should have changelog entries in English and German. :-)

**Comment by meikpiep** [comment]
Works: https://f-droid.org/de/packages/org.piepmeyer.gauguin/ :-)

Thanks for reporting, @Naomitr0n !

**Comment by Naomitr0n** [comment]
You're very welcome! :) Can confirm this works as intended, release notes show on my end too.
