### ISSUE TITLE
When starting a new game, the old game flashes on the screen

### ISSUE THREAD

**Issue by avipars** [meikpiep/gauguin#45]
When I initiate a new game, the solution flashes on the screen for a good second and then disappears. 

Is there any way to fix this?

**Comment by meikpiep** [comment]
This will very likely be the previous game which is currently used by the animation when switching from the new game screen to the main screen.
I you see the solution of the new game, give a ping here.

I will have a look if I can fix the animation or deactivate it if there is no quick fix.

Thanks for reporting!

**Comment by avipars** [comment]
it is indeed from the previous game.

I have animations set to 0.5x (via android developer settings), which is why it probably flashes so quickly

**Comment by meikpiep** [comment]
I just released version 0.18.0 containing the fix: https://github.com/meikpiep/gauguin/releases/tag/v0.18.0

Should be ready via Play store in the next 24 hours. F-Droid will take 2-4 days.
