### ISSUE TITLE
Unclear meaning of the number in the top bar

### ISSUE THREAD

**Issue by mccartney** [meikpiep/gauguin#47]
I fail to understand what the number 42 is supposed to mean here.
![Screenshot_20231215-220618.jpg](https://github.com/meikpiep/gauguin/assets/762437/72fdf25a-e9bf-40e1-82cb-10035f270d6b)

I can only guess the stars indicate difficulty.

**Comment by meikpiep** [comment]
Will be clickable in the future, with a popup/tooltip to explain the value and the star ranking.

Its indeed the difficulty value: For each cage, the number of different combinations of cell numbers which fulfill the result of the cage where multiplicated. The result is the natural logarithm. This is by far not optimal as it does not match the difficulty of every game, but works kind of okay.

**Comment by mccartney** [comment]
Thanks for the explanation.

BTW, not sure if intended, but I always see 4 (empty) stars next to the number. Even in a 2x2 game.

**Comment by meikpiep** [comment]
Just released version 0.17.0 https://github.com/meikpiep/gauguin/releases/tag/v0.17.0, containing a popup if tapping on the info of the top bar explaining the difficulty bounds. I will leave this issue open and supply a link or direct explanation how the difficulty rating gets calculated.

Nevertheless, the difficulties of 2x2 grids are not yet included as they would be 0.0 regardless of the difficulty level which is some kind of weird to display.

**Comment by mccartney** [comment]
Thank you!

And these four star symbols? What are they? It seems like they hard-coded, I always see exactly 4 of them.

**Comment by mccartney** [comment]
Thank you. Alles klar. I will try it out in practice with various game variants.

**Comment by meikpiep** [comment]
FYI: 0.17.0 is available via F-Droid.

**Comment by meikpiep** [comment]
I'm closed this issue. If anything is still unclear about the top bar, feel free to submit a new issue.
