### ISSUE TITLE
Starting a new game resets the streak in the statistics

### ISSUE THREAD

**Issue by mccartney** [meikpiep/gauguin#49]
No single step here seems wrong, but the overall scenario is suboptimal:

1. Play a game and complete it
2. Observe the confetti
3. Decide to play a new game, hit the blue plus icon
4. Make up your mind and decide you want a new game, but using different settings
5. Use the context menu to start the new game with selection

Expected:
1. The streak should be kept

Observed:
Streak goes to 0

**Comment by meikpiep** [comment]
Fixed in Main, gets into next release.

**Comment by meikpiep** [comment]
FYI: I just released version 0.16.0 https://github.com/meikpiep/gauguin/releases/tag/v0.16.0, including the fix.

Should be ready via Google play in a few hours and via F-Droid in 3-6 days.
Thanks for reporting!

**Comment by meikpiep** [comment]
FYI: The F-Droid build has failed due to my fault, the next version 0.16.1 fixes is, but will be ready an 2-6 days, sorry for the delay.

**Comment by meikpiep** [comment]
FYI: Version 0.16.1 containing this fix arrived at F-Droid.
