### ISSUE TITLE
Single cells could come prefilled

### ISSUE THREAD

**Issue by mccartney** [meikpiep/gauguin#50]
I think it'd be nice if the single-cell cages came prefilled.

**Comment by mccartney** [comment]
Slightly related to #27

**Comment by meikpiep** [comment]
I just added a preference to fill single cells. Will be included in the next release.

**Comment by meikpiep** [comment]
I just released version 0.18.0 containing this feature: https://github.com/meikpiep/gauguin/releases/tag/v0.18.0

Should be ready via Play store in the next 24 hours. F-Droid will take 2-4 days.
