### ISSUE TITLE
"Puzzle Solved" message from the old game shows even in new game

### ISSUE THREAD

**Issue by isHiteshBehera** [meikpiep/gauguin#54]
After completing a puzzle, the message "Puzzle Solved!" appears.

And then after starting a new game by clicking the Blue "+" button in the button, the message remains on the screen for some time even when the new puzzle has started.

Due to this, the number buttons are not accessible to use and the timer too runs out for few seconds

**Comment by meikpiep** [comment]
Thanks for reporting, should be fixed easily.

**Comment by meikpiep** [comment]
The fix will be included in the next release.

**Comment by meikpiep** [comment]
Just released version 0.17.0 https://github.com/meikpiep/gauguin/releases/tag/v0.17.0, containing this fix.

Will be available in a day via play store and 2-4 days via F-Droid.

**Comment by meikpiep** [comment]
FYI: Is now available via F-Droid.
