### ISSUE TITLE
"Fill single cages at start" doesn't clear pencil marks

### ISSUE THREAD

**Issue by mueller-ma** [meikpiep/gauguin#68]
When enabling "Fill single cages at start", "Begin with filled pencil marks" and "Auto-remove pencil marks" the single cages are filled, but the pencil marks in these cages aren't cleared and the marks in the same row/column also not.

**Comment by meikpiep** [comment]
Just fixed in main, will be included in next version.

Thanks for the reports and your effort!

**Comment by mueller-ma** [comment]
Thank you for this app :)

**Comment by meikpiep** [comment]
Just released version 0.19.1 with this fix: https://github.com/meikpiep/gauguin/releases/tag/v0.19.1

Should be online via Google Play until tomorrow, F-Droid will need 2-4 days.

**Comment by meikpiep** [comment]
FYI: 0.19.1 finally arrived today via F-Droid.
