### ISSUE TITLE
Resetting game doesn't clear highlights

### ISSUE THREAD

**Issue by s0lst1ce** [meikpiep/gauguin#70]
Thanks for the awesome game !

I have however noticed that when you reset a game when some tiles are still highlighted (say after setting a value which affects the suggestions in others), the highlights remain on the new, empty, board.

**Comment by meikpiep** [comment]
Just released version 0.19.1 with this fix: https://github.com/meikpiep/gauguin/releases/tag/v0.19.1

Should be online via Google Play until tomorrow, F-Droid will need 2-4 days.

**Comment by meikpiep** [comment]
FYI: 0.19.1 finally arrived today via F-Droid.
