### ISSUE TITLE
Octal numeral system leads to misleading display of cell values

### ISSUE THREAD

**Issue by sideria** [meikpiep/gauguin#77]
![Screenshot_20240209-200302_Gauguin](https://github.com/meikpiep/gauguin/assets/77381736/90d4acf0-c713-4431-86e3-02b0b052967f)

**Comment by meikpiep** [comment]
Tricky thing... you have chosen an octal base as the number system. Thus,
- the 10 in the upper left corner means 1*8 + 0 = 8 in decimal system
- the 24 at the bottom means 2 * 8 + 4 = 20 in decimal system

To use the common decimal system, use the new game dialog, choose the tab called "numbers" and set the bottom option to "decimal".

**Comment by meikpiep** [comment]
I will add a small icon at a corner of the game screen to indicate such non-decimal bases.

**Comment by meikpiep** [comment]
I will close this issue - if my analyze does not fit to your situation or you need any further help, feel free to add an comment here and reopen the issue.

**Comment by meikpiep** [comment]
Added a additional icon to the game screen if a non-decimal base is used. Thanks for reporting!

FYI: Included in version 0.21.0 https://github.com/meikpiep/gauguin/releases/tag/v0.21.0. It will be available via Play Store ~tomorrow and via F-Droid in ~3-6 days.
