### ISSUE TITLE
It is not possible to restart the game after solved

### ISSUE THREAD

**Issue by MageDelfador** [meikpiep/gauguin#79]

**Comment by meikpiep** [comment]
Confirmed, will be fixed soon, thanks for reporting.

**Comment by meikpiep** [comment]
FYI: Included in version 0.21.0 https://github.com/meikpiep/gauguin/releases/tag/v0.21.0. It will be available via Play Store ~tomorrow and via F-Droid in ~3-6 days.

**Comment by MageDelfador** [comment]
In version 0.21.0 the issue persists

**Comment by meikpiep** [comment]
Will be fixed in the next version.
