### ISSUE TITLE
Improve the UX of the Hint Snackbar

### ISSUE THREAD

**Issue by tuxiqae** [meikpiep/gauguin#83]
I feel like the [Hint Snackbar](https://github.com/meikpiep/gauguin/blob/995b69dfd9a08682de6011f88b55c2bca846c930/gauguin-app/src/main/kotlin/org/piepmeyer/gauguin/ui/main/MainActivity.kt#L385) (the one which pops when the `?` button is clicked during a game) is annoying since it obstructs the view and doesn't allow the player to dismiss it without waiting.

I thought of the following options of improving the current UX:
- Move the `?` button (easy to click on while playing)
- Move the bar to a different area (top of screen?)
- Allow dismissing the Snackbar ([regression of v0.20.0](https://github.com/meikpiep/gauguin/commit/2d7c1252a3f11dc6e04866add4eec37cf52663ff))

P.S. Seems like the dismissal isn't possible anymore since the Snackbar now gets created in the `binding.root` context, which doesn't have a `CoordinatorLayout` in its view hierarchy, I'm not an Android dev, hopefully I'm not misdirecting you.
> Having a CoordinatorLayout in your view hierarchy allows Snackbar to enable certain features, such as swipe-to-dismiss and automatically moving of widgets.

[Source](https://developer.android.com/reference/com/google/android/material/snackbar/Snackbar)

P.S.S. I would really appreciate solving that since I am currently unable to beat my top score of 34 seconds in 6x6 Fibonacci mode :sweat_smile:

**Comment by meikpiep** [comment]
Thanks for your detailed report!

I will analyze it in the next few days.

One question: What exactly avoids a new best time with 0.20.0? Can't you just ignore the snack bar and go on with filling numbers? I ask to gather further understanding and to avoid missing a point.

**Comment by meikpiep** [comment]
@tuxiqae Did not mention you in my previous questions, an answer would still be helpful.

I'm working on a dismissable popup which does not cover relevant parts of the grid or keypad.

**Comment by meikpiep** [comment]
Fixed in main via new implementation of the popup which may be dismissed by a tap at any point of the screen.

Included in version 0.21.0 https://github.com/meikpiep/gauguin/releases/tag/v0.21.0. It will be available via Play Store ~tomorrow and via F-Droid in ~3-6 days.
