### ISSUE TITLE
Mittelwert in English

### ISSUE THREAD

**Issue by mccartney** [meikpiep/gauguin#84]
The English translation contains untranslated "Mittelwert" in the statistics.

![Screenshot_20240217-140248.jpg](https://github.com/meikpiep/gauguin/assets/762437/9925888b-81c8-4522-93d0-520fb931cc18)

0.20.0

**Comment by meikpiep** [comment]
Just merged the fix, will get into next release.

**Comment by meikpiep** [comment]
FYI: Included in version 0.21.0 https://github.com/meikpiep/gauguin/releases/tag/v0.21.0. It will be available via Play Store ~tomorrow and via F-Droid in ~3-6 days.
