### ISSUE TITLE
error in calculation

### ISSUE THREAD

**Issue by ExploWare** [meikpiep/gauguin#85]
![Screenshot_20240218-090301](https://github.com/meikpiep/gauguin/assets/6767397/adc920a8-12af-4af1-9e3b-a79b1bc18584)
![Screenshot_20240218-090258](https://github.com/meikpiep/gauguin/assets/6767397/9184003f-1851-40aa-801c-06f60842a611)
I think these images are the only feedback I can supply on this.
On versiom 0.20.0

**Comment by meikpiep** [comment]
Thanks for reporting.

I first thought the first screenshot includes an obvious bug, as 6 * (3 + 3) * 1 = 36. But the operation as multiplication, such that 6 * 3 * 3 * 1 = 54. This leads to the red cells of the cage as the values do not match the result.

Was this the problem you had? Or do you mean something different?

**Comment by ExploWare** [comment]
You are so right. 
The eror in calculation appears to be mine..
Thanks for the quick feedback
