### ISSUE TITLE
Graphs in statistics are surprisingly horizontally scrollable

### ISSUE THREAD

**Issue by mccartney** [meikpiep/gauguin#88]
At first I was surprised after completing a game to see no visible indication of the stats changing. It turned out the graphs are horizontally scrollable, but there is nothing in the UI which would suggest that.
![Screenshot_20240218-230135.jpg](https://github.com/meikpiep/gauguin/assets/762437/20aadcaf-526a-40fa-8d8b-0880c7165963)

![Screenshot_20240218-230147.jpg](https://github.com/meikpiep/gauguin/assets/762437/79bf592d-d26a-4a8b-bf49-48fc293a26cf)

## Expectations/ideas

- either show a scrollbar
- or make the chart horizontally denser - i.e. fit the whole axis in viewport width
- or clip the history to show at most N last games (data points)
- or possibly other solutions

**Comment by mccartney** [comment]
Also it didn't occur to me that the charts are zoomable with two-finger gestures.

**Comment by meikpiep** [comment]
They were not intended to be scrollable, I will have a look if a simple configuration switch exists of the diagram library used called Vivo.

**Comment by meikpiep** [comment]
Solved in main, will be included in the next release.

**Comment by meikpiep** [comment]
FYI: Included in version 0.21.0 https://github.com/meikpiep/gauguin/releases/tag/v0.21.0. It will be available via Play Store ~tomorrow and via F-Droid in ~3-6 days.
